### ISSUE TITLE
2.0 Support

### ISSUE THREAD

**Issue by coolrecep** [maximegmd/CyberEngineTweaks#852]
Hi,

Could you please add 2.0 support? I have the build if you need any files or testing.

**Comment by FranklinS12** [comment]
They are working on it and need time to update.

**Comment by InnovatorNZ** [comment]
looking forwarding to 2.0 support~~~

**Comment by GhuronZhan** [comment]
Ganbatte kudasai ! // Bon courage !

**Comment by Lakori4** [comment]
pls, don't crunch it!

**Comment by booba-enjoyer** [comment]
crunch as needed, I want to play 2.0 with mods now

**Comment by CelinaxCute** [comment]
> crunch as needed, I want to play 2.0 with mods now

then code it by ur self when u cant wait

**Comment by CasualDev242** [comment]
Some people are really entitled. If you can't wait then get another hobby, perhaps a girlfriend (if possible)?

**Comment by booba-enjoyer** [comment]
> > crunch as needed, I want to play 2.0 with mods now
> 
> then code it by ur self when u cant wait

people are already doing it (for free), no need to get myself involved

**Comment by 0xF5F5F5** [comment]
> crunch as needed, I want to play 2.0 with mods now

LOL
also, booba-enjoyer, you're making other booba enjoyers look bad. We struggle enough

**Comment by 0xF5F5F5** [comment]
> Some people are really entitled. If you can't wait then get another hobby, perhaps a girlfriend (if possible)? 

I think he's trolling. If not, then he reminds me of those kids/idiots who pester people for iOS jailbreaks when a new iOS CVE is posted:

1. Find iOS security researcher on Twitter.

2. Reply "ETA when?" to every thread they start.

**Comment by CasualDev242** [comment]
Based on his profile, pretty sue he's a Russian aka a fucking moron.

**Comment by DartPower** [comment]
> Based on his profile, pretty sure he's a Russian aka a fucking moron. Drink some wodka for me.

This is not a place for politics, racism and nationalism.

**Comment by hiloyt** [comment]
> > Based on his profile, pretty sure he's a Russian aka a fucking moron. Drink some wodka for me.
> 
> This is not a place for politics, racism and nationalism.

This is also not a place to be disrespectful to authors, but you did not admonish booba-enjoyer :).

**Comment by H3ADROOM** [comment]
> Based on his profile, pretty sure he's a Russian aka a fucking moron. Drink some wodka for me.

based

**Comment by EvilCasper0** [comment]
Thank you so much for your continued support of this CP2077 tool nad mod. Your work is appreciated.

**Comment by hampta** [comment]
> > Based on his profile, pretty sure he's a Russian aka a fucking moron. Drink some wodka for me.
> 
> This is not a place for politics, racism and nationalism. 

And this is said by a person who subscribes to pro-Russian groups on VK (Russian social network)🤡

**Comment by H3ADROOM** [comment]
> > Based on his profile, pretty sure he's a Russian aka a fucking moron. Drink some wodka for me.
> 
> This is not a place for politics, racism and nationalism.

Says the person who is subscribed to shit like "Мемы про ХОХЛОВ" (Translation - "Memes about hohols". Hohol is an ethnic slur commonly used by Russians or pro-russians to harass Ukrainian people). I don't want to discuss politics on GitHub, but the way a person who supports racial harassment while trying to accuse someone of doing that is just a pure comedy.

**Comment by Lakori4** [comment]
tf has happened???
stfu.

**Comment by CapnLimbless** [comment]
Posting this with my legit profile because I ain't ashamed. Never seen code that came out of Russia that looked good. Also never met a Russian coder who wasn't also bigoted in multiple ways. I said it. Deny that sh*t.

**Comment by Giotje** [comment]
> Posting this with my legit profile because I ain't ashamed. Never seen code that came out of Russia that looked good. Also never met a Russian coder who wasn't also bigoted in multiple ways. I said it. Deny that sh*t.
 
damn bro you really got 'em

**Comment by Kyora473** [comment]
People are here to await a beloved and longstanding passion project's next update. Please take your soggy twitter takes some place else.

**Comment by CapnLimbless** [comment]
> People are here to await a beloved and longstanding passion project's next update. Please take your soggy twitter takes some place else.

If anyone wants to delete messages, I don't think any of us care. The idea though that where stuff comes from and who makes it doesn't matter, is just a desire of people who only want stuff without judgement. People here are reacting with legitimate resentment towards Russia and its people, based on the actions and culture of that country. Doing that anywhere and everywhere is how you respond culturally to people who allow a government you disapprove of. By the same token, as an American, I would pretty much expect to be hazed off any tech forum based in Iraq.

**Comment by Swapner** [comment]
You talk about Russians as if we are all the same. This is equivalent to saying that all, for example, Americans are imperialists and colonialists, because they allowed the invasion of many countries under imaginary pretexts. But that's stupid.
But you continue to divide everything into black and white: Russia and the Russians are absolute evil and ungrateful, not even people anymore, apparently, right? And the rest of the, undoubtedly, “civilized world” are noble elves.

**Comment by CapnLimbless** [comment]
> You talk about Russians as if we are all the same. This is equivalent to saying that all, for example, Americans are imperialists and colonialists, because they allowed the invasion of many countries under imaginary pretexts. But that's stupid. But you continue to divide everything into black and white: Russia and the Russians are absolute evil and ungrateful, not even people anymore, apparently, right? And the rest of the, undoubtedly, “civilized world” are noble elves.

You're trying to put straw man arguments in my mouth to make your position defensible. We know there are a lot of decent, normal people in Russia. But less of them are protesting and giving a crap than Americans were at the most popular parts of our Middle East wars. Get out in the street and we'll have good faith conversations with you. As long as the majority of Russains are pretending it's not a big deal, don't expect a warm global reception.

**Comment by Giotje** [comment]
people arguing on github is probably the dumbest thing i've seen since the acquisition of Twitter by Elon Musk

**Comment by Giotje** [comment]
we're here to play a game calm down

**Comment by Giotje** [comment]
also Phantom Liberty dropping in 5 minutes get ready chooms

**Comment by CapnLimbless** [comment]
> we're here to play a game calm down

Again, same thing. Stuff is happening in the world. Saying you just wanna play a game and have it not exist here is not cool with a lot of us. GitHub is an excellent place right now to find Russians trying to act like everything is cool, while in the next room their parents are watching state TV. You wanna escape completely, don't go on the internet until it's over. Otherwise some is gonna seep in everywhere because it's real to a lot of us, all the time. That being said, we all deserve some responsible escapism. Let's play PL.

**Comment by Swapner** [comment]
> > You talk about Russians as if we are all the same. This is equivalent to saying that all, for example, Americans are imperialists and colonialists, because they allowed the invasion of many countries under imaginary pretexts. But that's stupid. But you continue to divide everything into black and white: Russia and the Russians are absolute evil and ungrateful, not even people anymore, apparently, right? And the rest of the, undoubtedly, “civilized world” are noble elves.
> 
> You're trying to put straw man arguments in my mouth to make your position defensible. We know there are a lot of decent, normal people in Russia. But less of them are protesting and giving a crap than Americans were at the most popular parts of our Middle East wars. Get out in the street and we'll have good faith conversations with you. As long as the majority of Russains are pretending it's not a big deal, don't expect a warm global reception.

I’ll tell you a secret (no), but the majority of Russians, in principle, have always been:
1. Apolitical;
2. They loved and respected Western culture (until recently. Although even now, in general, many people are impressed by this culture, cinema, etc., but not by the governments of these countries. Please do not confuse the population and the government, which, by imposing sanctions, makes things worse not to the top in the form of olegarchs and other things, but to ordinary people).
Moreover, even now, when Russia and Russians have been disconnected from Swift, for the most part we don’t go downloading everything on torrents, but try to buy goods (games, movies, music) in one way or another.

So why did I write this? I'm not trying to justify my position (I didn't even voice it, lol), I'm just showing how what was written here earlier sounds strange and a little... Nazi? Because we are presented as ungrateful, untargeted, incompetent subhumans.

I am sure that all my words are an empty phrase for you, as well as for others. This is all just from the category of “It’s boiled over”, and therefore, I think I’ll retreat and distance myself from further dialogue with you or anyone else.

Oh yes, my position: any war is bad, no matter where it is and what values it pursues, because people die in it.
But even so, I wish my country victory, because no matter what the country is, the people in it are not to blame for the fact that the government is idiots.
This applies to your countries too.

Thank you if you read it. Good luck to you and I sincerely hope that everything goes well for you.

**Comment by Giotje** [comment]
> > we're here to play a game calm down
> 
> Again, same thing. Stuff is happening in the world. Saying you just wanna play a game and have it not exist here is not cool with a lot of us. GitHub is an excellent place right now to find Russians trying to act like everything is cool, while in the next room their parents are watching state TV. You wanna escape completely, don't go on the internet until it's over. Otherwise some is gonna seep in everywhere because it's real to a lot of us, all the time. That being said, we all deserve some responsible escapism. Let's play PL.

that's crazy bro phantom liberty is out rn

**Comment by CapnLimbless** [comment]
> > > You talk about Russians as if we are all the same. This is equivalent to saying that all, for example, Americans are imperialists and colonialists, because they allowed the invasion of many countries under imaginary pretexts. But that's stupid. But you continue to divide everything into black and white: Russia and the Russians are absolute evil and ungrateful, not even people anymore, apparently, right? And the rest of the, undoubtedly, “civilized world” are noble elves.
> > 
> > 
> > You're trying to put straw man arguments in my mouth to make your position defensible. We know there are a lot of decent, normal people in Russia. But less of them are protesting and giving a crap than Americans were at the most popular parts of our Middle East wars. Get out in the street and we'll have good faith conversations with you. As long as the majority of Russains are pretending it's not a big deal, don't expect a warm global reception.
> 
> I’ll tell you a secret (no), but the majority of Russians, in principle, have always been:
> 
> 1. Apolitical;
> 2. They loved and respected Western culture (until recently. Although even now, in general, many people are impressed by this culture, cinema, etc., but not by the governments of these countries. Please do not confuse the population and the government, which, by imposing sanctions, makes things worse not to the top in the form of olegarchs and other things, but to ordinary people).
>    Moreover, even now, when Russia and Russians have been disconnected from Swift, for the most part we don’t go downloading everything on torrents, but try to buy goods (games, movies, music) in one way or another.
> 
> So why did I write this? I'm not trying to justify my position (I didn't even voice it, lol), I'm just showing how what was written here earlier sounds strange and a little... Nazi? Because we are presented as ungrateful, untargeted, incompetent subhumans.
> 
> I am sure that all my words are an empty phrase for you, as well as for others. This is all just from the category of “It’s boiled over”, and therefore, I think I’ll retreat and distance myself from further dialogue with you or anyone else.
> 
> Oh yes, my position: any war is bad, no matter where it is and what values it pursues, because people die in it. But even so, I wish my country victory, because no matter what the country is, the people in it are not to blame for the fact that the government is idiots. This applies to your countries too.
> 
> Thank you if you read it. Good luck to you and I sincerely hope that everything goes well for you.

Oh boy, an educator. Your message says everything needed to identify yourself as who I and many other Westerners have a problem with. You don't get to be apolitical when your country is starting wars. We know that pretty well here. THAT is what people did in Nazi Germany, if you're gonna go there. 

You should also look up the definition of the word "empire." If Nato countries were invading other nations to take their land and repopulate it with our citizens, we would have a pretty huge issue with that. That's not what we do. We invade people to preserve our philosophy of a global society and economy by neutralizing them as a threat. We have proven we will totally walk away and let those countries rot afterwards. Not an angelic position at all, but a clear different philosophy of government if you understand it.

My position is pretty clear and has nothing to do with what you are trying to say. I am hostile to all Russains who do anything rude, entitled or aggressive on the internet at all. Because I want them to feel uncomfortable and wonder why everyone is so mad at them. Maybe look more at information from outside Russia.

**Comment by Giotje** [comment]
phantom liberty is pretty good

**Comment by maximegmd** [comment]
My god can't you guys just behave, keep your political shit out of my github.
